site_name: SIGFuchsia-Doc
site_url: https://sigfuchsia.github.io/doc/
theme:
  name: material
nav:
  - Home: index.md
  - Basic: 
    - Basic: basic/basic.md
  - Play:
    - 'DoS on Fuchsia': play/dos.md
    - 'Boot Fuchsia on NUC': play/boot.md
    - 'Run Self-built Component': play/performance.md
  - Troubles: 
    - '[Solved] QT Missing xcb': troubles/qt-missing-xcb.md
    - '[Solved] Missing ktrace-dump': troubles/missing-ktrace-dump.md
    - 'Missing Partition when Booting on NUC': troubles/nuc-boot-missing-partition.md
  - About: about.md
markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
