site_name: SIGFuchsia-Doc
site_url: https://sigfuchsia.github.io/doc/
theme:
  name: material
nav:
  - Home: index.md
  - Basic: 
    - Basic: basic/basic.md
  - Troubles: 
    - 'QT Missing xcb': troubles/qt-missing-xcb.md
    - '[Solved] Missing ktrace-dump': troubles/missing-ktrace-dump.md
  - About: about.md
markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences