name: Markdown Lint
on: 
  push:
    branches-ignore:
      - 'gh-pages'

jobs:
  build:
    name: Markdown Lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: nosborn/github-action-markdown-cli@v2
      name: Markdown Lint
      with:
        files: .
        config_file: ".markdownlint.json"
